// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * EIGRP compact event log.
 *
 * Copyright (C) 2026 Donnie V. Savage
 */
#ifndef EIGRPD_EIGRP_EVENTLOG_H_
#define EIGRPD_EIGRP_EVENTLOG_H_

#include <stddef.h>
#include <stdint.h>

#include "eigrp_cli.h"
#include "eigrp_mgnt.h"
#include "eigrp_instance.h"
#include "eigrp.h"
#include "eigrp_types.h"

#define EIGRP_EVENTLOG_DEFAULT_SIZE 500U

typedef enum eigrp_eventlog_opcode {
	EIGRP_EVENTLOG_OPCODE_NONE = 0,
	EIGRP_EVENTLOG_OPCODE_IPV6_NO_ROUTER_ID,
	EIGRP_EVENTLOG_OPCODE_DUAL_STATE_CHANGE,
	EIGRP_EVENTLOG_OPCODE_NEIGHBOR_STATE_CHANGE,
	EIGRP_EVENTLOG_OPCODE_PACKET_RX,
	EIGRP_EVENTLOG_OPCODE_PACKET_TX,
	EIGRP_EVENTLOG_OPCODE_RTP_ACK,
	EIGRP_EVENTLOG_OPCODE_RTP_RETRANSMIT,
	EIGRP_EVENTLOG_OPCODE_RTP_RETRY_LIMIT,
	EIGRP_EVENTLOG_OPCODE_SUMMARY_METRIC,
	EIGRP_EVENTLOG_OPCODE_SUMMARY_COMPONENT,
	EIGRP_EVENTLOG_OPCODE_SUMMARY_WITHDRAW,
	EIGRP_EVENTLOG_OPCODE_RIB_ROUTE_UPDATE,
	EIGRP_EVENTLOG_OPCODE_RIB_ROUTE_DELETE,
	EIGRP_EVENTLOG_OPCODE_REDIST_ROUTE_UPDATE,
	EIGRP_EVENTLOG_OPCODE_REDIST_ROUTE_WITHDRAW,
	EIGRP_EVENTLOG_OPCODE_REDIST_ROUTE_FILTERED,
	EIGRP_EVENTLOG_OPCODE_REDIST_ROUTE_REJECT,
	EIGRP_EVENTLOG_OPCODE_DUAL_METRIC_SET,
	EIGRP_EVENTLOG_OPCODE_DUAL_FIND_FS,
	EIGRP_EVENTLOG_OPCODE_DUAL_FC_SAT,
	EIGRP_EVENTLOG_OPCODE_DUAL_FC_NOT_SAT,
	EIGRP_EVENTLOG_OPCODE_DUAL_ACTIVE_PEERS,
	EIGRP_EVENTLOG_OPCODE_QUERY_RX,
	EIGRP_EVENTLOG_OPCODE_REPLY_RX,
	EIGRP_EVENTLOG_OPCODE_REPLY_TX,
	EIGRP_EVENTLOG_OPCODE_REPLY_STATUS,
	EIGRP_EVENTLOG_OPCODE_TOPOLOGY_ROUTE_DELETE,
	EIGRP_EVENTLOG_OPCODE_UPDATE_PACKETIZED,
	EIGRP_EVENTLOG_OPCODE_POISON_REVERSE,
	EIGRP_EVENTLOG_OPCODE_NSF_EVENT,
	EIGRP_EVENTLOG_OPCODE_SIA_QUERY_TX,
	EIGRP_EVENTLOG_OPCODE_SIA_QUERY_RX,
	EIGRP_EVENTLOG_OPCODE_SIA_REPLY_TX,
	EIGRP_EVENTLOG_OPCODE_SIA_REPLY_RX,
	EIGRP_EVENTLOG_OPCODE_SIA_EXPIRE,
	EIGRP_EVENTLOG_OPCODE_PACKET_REJECT,
	EIGRP_EVENTLOG_OPCODE_ROUTE_FILTERED,
	EIGRP_EVENTLOG_OPCODE_OFFSET_APPLIED,
	EIGRP_EVENTLOG_OPCODE_PREFIX_LIMIT_REJECT,
	EIGRP_EVENTLOG_OPCODE_PREFIX_LIMIT_PEER,
	EIGRP_EVENTLOG_OPCODE_RIB_INSTALL,
	EIGRP_EVENTLOG_OPCODE_RIB_WITHDRAW,
	EIGRP_EVENTLOG_OPCODE_ROUTE_ENCODE_FAILURE,
	EIGRP_EVENTLOG_OPCODE_PACKET_TX_FAILURE,
	EIGRP_EVENTLOG_OPCODE_RTP_ACK_UNEXPECTED,
	EIGRP_EVENTLOG_OPCODE_PEER_CAPABILITY,
	EIGRP_EVENTLOG_OPCODE_INTERFACE_STATE,
	EIGRP_EVENTLOG_OPCODE_SUCCESSOR_CHANGE,
} eigrp_eventlog_opcode_t;

typedef enum eigrp_eventlog_neighbor_reason {
	EIGRP_EVENTLOG_NEIGHBOR_REASON_NONE = 0,
	EIGRP_EVENTLOG_NEIGHBOR_REASON_HOLD_EXPIRED,
	EIGRP_EVENTLOG_NEIGHBOR_REASON_K_MISMATCH,
	EIGRP_EVENTLOG_NEIGHBOR_REASON_GOODBYE,
	EIGRP_EVENTLOG_NEIGHBOR_REASON_PEER_RESTART,
	EIGRP_EVENTLOG_NEIGHBOR_REASON_RTP_RETRY_LIMIT,
	EIGRP_EVENTLOG_NEIGHBOR_REASON_ADMIN_CLEAR,
	EIGRP_EVENTLOG_NEIGHBOR_REASON_INTERFACE_DOWN,
	EIGRP_EVENTLOG_NEIGHBOR_REASON_PEER_TERMINATION,
	EIGRP_EVENTLOG_NEIGHBOR_REASON_SIA,
} eigrp_eventlog_neighbor_reason_t;

typedef enum eigrp_eventlog_packet_reject_reason {
	EIGRP_EVENTLOG_PACKET_REJECT_NONE = 0,
	EIGRP_EVENTLOG_PACKET_REJECT_BOUNDS,
	EIGRP_EVENTLOG_PACKET_REJECT_PASSIVE_INTERFACE,
	EIGRP_EVENTLOG_PACKET_REJECT_SHORT_HEADER,
	EIGRP_EVENTLOG_PACKET_REJECT_VERSION,
	EIGRP_EVENTLOG_PACKET_REJECT_AS_MISMATCH,
	EIGRP_EVENTLOG_PACKET_REJECT_VRID_MISMATCH,
	EIGRP_EVENTLOG_PACKET_REJECT_CHECKSUM,
	EIGRP_EVENTLOG_PACKET_REJECT_SOURCE_OFFLINK,
	EIGRP_EVENTLOG_PACKET_REJECT_AUTH_TLV_FRAMING,
	EIGRP_EVENTLOG_PACKET_REJECT_AUTH_UNEXPECTED,
	EIGRP_EVENTLOG_PACKET_REJECT_AUTH_NO_KEY,
	EIGRP_EVENTLOG_PACKET_REJECT_AUTH_MISSING,
	EIGRP_EVENTLOG_PACKET_REJECT_AUTH_NOT_FIRST,
	EIGRP_EVENTLOG_PACKET_REJECT_AUTH_TYPE_MISMATCH,
	EIGRP_EVENTLOG_PACKET_REJECT_AUTH_LENGTH,
	EIGRP_EVENTLOG_PACKET_REJECT_AUTH_UNSUPPORTED,
	EIGRP_EVENTLOG_PACKET_REJECT_AUTH_DIGEST,
	EIGRP_EVENTLOG_PACKET_REJECT_NO_NEIGHBOR,
	EIGRP_EVENTLOG_PACKET_REJECT_CR_NOT_ELIGIBLE,
	EIGRP_EVENTLOG_PACKET_REJECT_HELLO_TLV,
	EIGRP_EVENTLOG_PACKET_REJECT_STATIC_NEIGHBOR,
	EIGRP_EVENTLOG_PACKET_REJECT_HELLO_K_MISMATCH,
	EIGRP_EVENTLOG_PACKET_REJECT_UNSUPPORTED_OPCODE,
	EIGRP_EVENTLOG_PACKET_REJECT_NO_INTERFACE,
} eigrp_eventlog_packet_reject_reason_t;

typedef enum eigrp_eventlog_filter_reason {
	EIGRP_EVENTLOG_FILTER_REASON_NONE = 0,
	EIGRP_EVENTLOG_FILTER_REASON_DEFAULT_INFORMATION,
	EIGRP_EVENTLOG_FILTER_REASON_PROCESS,
	EIGRP_EVENTLOG_FILTER_REASON_INTERFACE,
} eigrp_eventlog_filter_reason_t;


typedef enum eigrp_eventlog_interface_state {
	EIGRP_EVENTLOG_INTERFACE_STATE_NONE = 0,
	EIGRP_EVENTLOG_INTERFACE_STATE_UP,
	EIGRP_EVENTLOG_INTERFACE_STATE_DOWN,
	EIGRP_EVENTLOG_INTERFACE_STATE_PASSIVE,
	EIGRP_EVENTLOG_INTERFACE_STATE_ACTIVE,
	EIGRP_EVENTLOG_INTERFACE_STATE_MULTICAST_JOIN_FAILED,
} eigrp_eventlog_interface_state_t;

typedef enum eigrp_eventlog_prefix_limit_scope {
	EIGRP_EVENTLOG_PREFIX_LIMIT_NONE = 0,
	EIGRP_EVENTLOG_PREFIX_LIMIT_NEIGHBOR,
	EIGRP_EVENTLOG_PREFIX_LIMIT_TOPOLOGY,
	EIGRP_EVENTLOG_PREFIX_LIMIT_REDISTRIBUTION,
} eigrp_eventlog_prefix_limit_scope_t;

/*
 * Event entries are self-contained snapshots.  addr is the primary address or
 * prefix for the event; scalar arguments must never retain pointers to mutable
 * EIGRP objects.  A logical operation may emit multiple compact records when
 * more context is required.
 */
/* Runtime ring lifecycle. */
eigrp_result_t eigrp_eventlog_init(eigrp_instance_t *eigrp, uint32_t capacity);
void eigrp_eventlog_delete(eigrp_instance_t *eigrp);
eigrp_result_t eigrp_eventlog_resize(eigrp_instance_t *eigrp,
				     uint32_t capacity);

/* Append one self-contained event snapshot to the bounded ring. */
eigrp_result_t eigrp_eventlog_msg_add(eigrp_instance_t *eigrp,
				     uint16_t opcode,
				     const eigrp_prefix_t *addr,
				     eventmsg_arg_t arg1,
				     eventmsg_arg_t arg2,
				     eventmsg_arg_t arg3,
				     eventmsg_arg_t arg4);
void eigrp_eventlog_addr_from_legacy(eigrp_prefix_t *prefix,
				     const eigrp_addr_t *addr);

/* Operational/configuration targets. */
eigrp_result_t eigrp_eventlog_clear(eigrp_instance_context_t *context);
eigrp_result_t eigrp_eventlog_size_update(eigrp_operation_t operation,
	eigrp_instance_context_t *context,
	uint32_t size);
eigrp_result_t eigrp_eventlog_state_read(
	const eigrp_instance_context_t *context, eigrp_eventlog_state_t *state);
eigrp_result_t eigrp_eventlog_msg_iterate(const eigrp_instance_context_t *context,
				   eigrp_eventlog_msg_cb callback,
				   void *arg);

/* Static opcode-to-format lookup and trusted formatter used by show adapters. */
const char *eigrp_eventlog_format_read(unsigned long opcode);
eigrp_result_t eigrp_eventlog_msg_format(const eigrp_eventlog_msg_t *entry,
					 char *buffer, size_t buffer_size);

#endif /* EIGRPD_EIGRP_EVENTLOG_H_ */
